" General Settings
set tabstop=2       " Tabs = 2 spaces
set shiftwidth=2    " Shifting with '>>' = 2 spaces
set expandtab       " Tabs are spaces
set number          " Show line numbers
set relativenumber  " Set relative line numbering
set showmatch       " Show matching brackets
set incsearch       " Search as you type
set ignorecase      " Case insensitive search
set list
set listchars=tab:›\ ,trail:•,extends:#,nbsp:. "

" Leader Key
let mapleader = ","

" Using arrows is for the weak
nnoremap <Leader><space> :noh<cr>
map <Left>  :echo "use h!"<cr>
map <Right> :echo "use l!"<cr>
map <Up>    :echo "use k!"<cr>
map <Down>  :echo "use j!"<cr>

" Stupid shift key fixes
if has("user_commands")
    command! -bang -nargs=* -complete=file E e<bang> <args>
    command! -bang -nargs=* -complete=file W w<bang> <args>
    command! -bang -nargs=* -complete=file Wq wq<bang> <args>
    command! -bang -nargs=* -complete=file WQ wq<bang> <args>
    command! -bang Wa wa<bang>
    command! -bang WA wa<bang>
    command! -bang Q q<bang>
    command! -bang QA qa<bang>
    command! -bang Qa qa<bang>
endif

" Visual shifting (does not exit Visual mode)
vnoremap < <gv
vnoremap > >gv

" Automatically Strip trailing whitespace on save
function! <SID>StripTrailingWhitespaces()
    " Preparation: save last search, and cursor position.
    let _s=@/
    let l = line(".")
    let c = col(".")
    " Do the business:
    %s/\s\+$//e
    " Clean up: restore previous search history, and cursor position
    let @/=_s
    call cursor(l, c)
endfunction
autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()

" Vim Plug - Plugin Installation
" https://github.com/junegunn/vim-plug
call plug#begin('~/.local/share/nvim/plugged')

  " https://github.com/ctrlpvim/ctrlp.vim
  Plug 'ctrlpvim/ctrlp.vim'

  " https://github.com/tpope/vim-commentary
  Plug 'tpope/vim-commentary'

  " https://github.com/JamshedVesuna/vim-markdown-preview
  Plug 'JamshedVesuna/vim-markdown-preview'

  " https://github.com/zhaocai/GoldenView.Vim
  Plug 'zhaocai/GoldenView.Vim'

  " https://github.com/frankier/neovim-colors-solarized-truecolor-only/
  Plug 'frankier/neovim-colors-solarized-truecolor-only'

  " https://github.com/terryma/vim-multiple-cursors
  Plug 'terryma/vim-multiple-cursors'

" Initialize plugin system
call plug#end()


" Plugin Settings
" Solarized
syntax enable
set background=dark
colorscheme solarized

" CtrP
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'

" Vim-Commentary
vmap <Bslash><Bslash> gc
nmap <Bslash><Bslash> gcgc
autocmd FileType python setlocal commentstring=#\ %s

" Markdown Preview
let vim_markdown_preview_hotkey='<C-m>'
let vim_markdown_preview_browser='Firefox'
let vim_markdown_preview_github=1

" Golden View
let g:goldenview__enable_default_mapping = 0
nmap <silent> <leader>w  <Plug>GoldenViewSplit
nmap <silent> <C-l>  <Plug>GoldenViewNext
nmap <silent> <C-h>  <Plug>GoldenViewPrevious

" Filetype specific settings
autocmd FileType python setlocal shiftwidth=4 softtabstop=4

" Use deoplete.
let g:deoplete#enable_at_startup = 1
