#!/bin/bash
alias aliases="vim $HOME/.aliases"

# Folders
alias p="cd ~/Projects"

# Grep-> Ripgrep
alias grep="rg"

# Vim
alias vim="nvim"
alias vi="vim"
alias v="vim"

# History
alias h="history"

# Netcat
alias nc="netcat"

# Navigation
# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
else # OS X `ls`
  colorflag="-G"
fi

# ls with permanent color output
alias ls="lsd"

# IP addresses
alias ip="curl http://canhazip.com"
alias localips="ifconfig | grep 'inet ' | cut -d ' ' -f2 | grep -v 127.0.0.1"

# Aliases using OS dependent flags
if [ $OSTYPE = 'linux-gnu' ]; then
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
  alias flush="/etc/init.d/dns-clean start"     # Flush Directory Service cache
else
  alias flush="dscacheutil -flushcache"         # Flush Directory Service cache
  alias cleanup="find . -name '*.DS_Store' -type f -ls -delete" # Recursively delete `.DS_Store` files
fi

# Pipe my public key to my clipboard.
alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | echo '=> Public key copied to pasteboard.'"

# File size
alias fs="stat -f \"%z bytes\""

alias weather="curl wttr.in/~Chambly"

alias emulator="~/Library/Android/sdk/emulator/emulator"
