# PATHs
export PATH="$PATH:/Applications/010 Editor.app/Contents/CmdLine"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$HOME/bin:$PATH"
export PATH="/usr/local/Caskroom/android-sdk/4333796:$PATH"
export PATH="/usr/local/Caskroom/android-sdk/4333796/tools:$PATH"
export PATH="/usr/local/opt/qt/bin/:$PATH"
export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.jenv/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$HOME/Library/pnpm:$PATH"

# Android SDK
export ANDROID_HOME=$HOME/Library/Android/sdk
export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export ANDROID_AVD_HOME=$HOME/.android/avd


# Source files
root=$HOME
source $root/.exports     # Various exports
source $root/.aliases     # User-defined aliases
source $root/.aliases.local     # Extra aliases
source $root/.secrets.local # Secrets
source $root/.bash_colors # Color codes
source $root/.bash_prompt # Bash prompt
source $root/.git-completion.bash # Git auto-complete

# Tab completion
if [[ "$OSTYPE" == "darwin"* ]]; then
  [ -f "$(brew --prefix)/etc/bash_completion" ] && source $(brew --prefix)/etc/bash_completion
fi

# Language environments
# which pyenv  >/dev/null && eval "$(pyenv init -)"
# which rbenv  >/dev/null && eval "$(rbenv init -)"
# which jenv   >/dev/null && eval "$(jenv init -)"

# fzf
# source ~/.fzf.bash
