# PATHs
export PATH="$PATH:/Applications/010 Editor.app/Contents/CmdLine"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/bin:$HOME/bin:$PATH"
export PATH="/usr/local/Caskroom/android-sdk/4333796:$PATH"
export PATH="/usr/local/Caskroom/android-sdk/4333796/tools:$PATH"
export PATH="/usr/local/opt/qt/bin/:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.jenv/bin:$PATH"
export PATH="$HOME/.phpenv/bin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"

[ -f /usr/libexec/java_home ] && export JAVA_HOME=$(/usr/libexec/java_home)

# Create aliases.local if doesn't exist
root=$HOME
touch $root/.aliases.local

# Source files
source $root/.exports     # Various exports
source $root/.aliases     # User-defined aliases
source $root/.aliases.local     # Extra aliases
source $root/.bash_colors # Color codes
source $root/.bash_prompt # Bash prompt
source $root/.git-completion.bash # Git auto-complete

# Tab completion
if [[ "$OSTYPE" == "darwin"* ]]; then
  [ -f "$(brew --prefix)/etc/bash_completion" ] && source $(brew --prefix)/etc/bash_completion
fi

# Initialize pyenv and rbenv
which pyenv  >/dev/null && eval "$(pyenv init -)"
which rbenv  >/dev/null && eval "$(rbenv init -)"
which jenv   >/dev/null && eval "$(jenv init -)"
which phpenv >/dev/null && eval "$(phpenv init -)"

# Initialize tmux if on OSX
[ -z "$TMUX" ] && [[ "$OSTYPE" == "darwin"* ]] && exec tmux attach

# fzf
source ~/.fzf.bash
